package com.biprangshu.guardiansathi.Global.presentation.login

import android.widget.Toast
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.biprangshu.guardiansathi.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import kotlinx.coroutines.launch

@Composable
fun LoginRoot(
    onNavigateToRegistration: () -> Unit,
    viewModel: LoginViewModel = hiltViewModel()
) {
    val state by viewModel.state.collectAsStateWithLifecycle()
    val context = LocalContext.current

    LaunchedEffect(Unit) {
        viewModel.events.collect { event ->
            when (event) {
                is LoginEvent.NavigateToRegistration -> onNavigateToRegistration()
                is LoginEvent.ShowError -> {
                    Toast.makeText(context, event.message, Toast.LENGTH_LONG).show()
                }
            }
        }
    }

    LoginScreen(
        state = state,
        onAction = viewModel::onAction
    )
}

@Composable
fun LoginScreen(
    state: LoginState,
    onAction: (LoginAction) -> Unit
) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    val credentialManager = remember { CredentialManager.create(context) }
    
    // Dynamically fetch the web client ID generated by google-services plugin
    // to avoid compile errors when google-services.json is missing.
    val webClientId = remember(context) {
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        if (resId != 0) context.getString(resId) else ""
    }

    fun handleCredentialResponse(credential: androidx.credentials.Credential) {
        if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
            onAction(LoginAction.OnGoogleSignInResult(googleIdTokenCredential.idToken, null))
        } else {
            onAction(LoginAction.OnGoogleSignInResult(null, "Unexpected credential type"))
        }
    }

    fun launchGoogleSignIn() {
        if (webClientId.isBlank()) {
            onAction(LoginAction.OnGoogleSignInResult(null, "Web Client ID is missing. Add google-services.json"))
            return
        }

        onAction(LoginAction.OnGoogleSignInClick)
        coroutineScope.launch {
            try {
                // Primary: credential picker (bottom sheet)
                val googleIdOption = GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(false)
                    .setServerClientId(webClientId)
                    .setAutoSelectEnabled(false)
                    .build()

                val result = credentialManager.getCredential(
                    request = GetCredentialRequest.Builder()
                        .addCredentialOption(googleIdOption)
                        .build(),
                    context = context
                )
                handleCredentialResponse(result.credential)
            } catch (e: NoCredentialException) {
                // Fallback: full-page Google Sign-In dialog — works even when
                // GetGoogleIdOption fails due to OAuth/SHA-1 configuration gaps
                try {
                    val signInWithGoogleOption = GetSignInWithGoogleOption.Builder(webClientId).build()
                    val fallbackResult = credentialManager.getCredential(
                        request = GetCredentialRequest.Builder()
                            .addCredentialOption(signInWithGoogleOption)
                            .build(),
                        context = context
                    )
                    handleCredentialResponse(fallbackResult.credential)
                } catch (e2: GetCredentialException) {
                    onAction(LoginAction.OnGoogleSignInResult(null, e2.message))
                }
            } catch (e: GetCredentialException) {
                onAction(LoginAction.OnGoogleSignInResult(null, e.message))
            } catch (e: Exception) {
                onAction(LoginAction.OnGoogleSignInResult(null, e.message))
            }
        }
    }

    Scaffold { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center
        ) {
            Text(text = "Login")
            Spacer(modifier = Modifier.height(32.dp))

            if (state.isLoading) {
                CircularProgressIndicator()
            } else {
                Button(onClick = { launchGoogleSignIn() }) {
                    Text("Sign in with Google")
                }
            }

            if (state.error != null) {
                Spacer(modifier = Modifier.height(16.dp))
                Text(text = "Error: ${state.error}", color = androidx.compose.ui.graphics.Color.Red)
            }
        }
    }
}

@Preview
@Composable
private fun LoginScreenPreview() {
    LoginScreen(state = LoginState(), onAction = {})
}