package com.biprangshu.guardiansathi.Global.presentation.login

import android.widget.Toast
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.biprangshu.guardiansathi.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import kotlinx.coroutines.launch

@Composable
fun LoginRoot(
    onNavigateToRegistration: () -> Unit,
    viewModel: LoginViewModel = hiltViewModel()
) {
    val state by viewModel.state.collectAsStateWithLifecycle()
    val context = LocalContext.current

    LaunchedEffect(Unit) {
        viewModel.events.collect { event ->
            when (event) {
                is LoginEvent.NavigateToRegistration -> onNavigateToRegistration()
                is LoginEvent.ShowError -> {
                    Toast.makeText(context, event.message, Toast.LENGTH_LONG).show()
                }
            }
        }
    }

    LoginScreen(
        state = state,
        onAction = viewModel::onAction
    )
}

@Composable
fun LoginScreen(
    state: LoginState,
    onAction: (LoginAction) -> Unit
) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    val credentialManager = remember { CredentialManager.create(context) }
    
    // Dynamically fetch the web client ID generated by google-services plugin
    // to avoid compile errors when google-services.json is missing.
    val webClientId = remember(context) {
        val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        if (resId != 0) context.getString(resId) else ""
    }

    fun handleCredentialResponse(credential: androidx.credentials.Credential) {
        if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
            onAction(LoginAction.OnGoogleSignInResult(googleIdTokenCredential.idToken, null))
        } else {
            onAction(LoginAction.OnGoogleSignInResult(null, "Unexpected credential type"))
        }
    }

    fun launchGoogleSignIn() {
        if (webClientId.isBlank()) {
            onAction(LoginAction.OnGoogleSignInResult(null, "Web Client ID is missing. Add google-services.json"))
            return
        }

        onAction(LoginAction.OnGoogleSignInClick)
        coroutineScope.launch {
            try {
                // Primary: credential picker (bottom sheet)
                val googleIdOption = GetGoogleIdOption.Builder()
                    .setFilterByAuthorizedAccounts(false)
                    .setServerClientId(webClientId)
                    .setAutoSelectEnabled(false)
                    .build()

                val result = credentialManager.getCredential(
                    request = GetCredentialRequest.Builder()
                        .addCredentialOption(googleIdOption)
                        .build(),
                    context = context
                )
                handleCredentialResponse(result.credential)
            } catch (e: NoCredentialException) {
                // Fallback: full-page Google Sign-In dialog — works even when
                // GetGoogleIdOption fails due to OAuth/SHA-1 configuration gaps
                try {
                    val signInWithGoogleOption = GetSignInWithGoogleOption.Builder(webClientId).build()
                    val fallbackResult = credentialManager.getCredential(
                        request = GetCredentialRequest.Builder()
                            .addCredentialOption(signInWithGoogleOption)
                            .build(),
                        context = context
                    )
                    handleCredentialResponse(fallbackResult.credential)
                } catch (e2: GetCredentialException) {
                    onAction(LoginAction.OnGoogleSignInResult(null, e2.message))
                }
            } catch (e: GetCredentialException) {
                onAction(LoginAction.OnGoogleSignInResult(null, e.message))
            } catch (e: Exception) {
                onAction(LoginAction.OnGoogleSignInResult(null, e.message))
            }
        }
    }

    Scaffold { padding ->
//        Column(
//            modifier = Modifier
//                .fillMaxSize()
//                .padding(padding)
//                .padding(16.dp),
//            horizontalAlignment = Alignment.CenterHorizontally,
//            verticalArrangement = Arrangement.Center
//        ) {
//            Text(text = "Login")
//            Spacer(modifier = Modifier.height(32.dp))
//
//            if (state.isLoading) {
//                CircularProgressIndicator()
//            } else {
//                Button(onClick = { launchGoogleSignIn() }) {
//                    Text("Sign in with Google")
//                }
//            }
//
//            if (state.error != null) {
//                Spacer(modifier = Modifier.height(16.dp))
//                Text(text = "Error: ${state.error}", color = androidx.compose.ui.graphics.Color.Red)
//            }
//        }
//
        Box(
            modifier = Modifier
                .fillMaxSize()
                .background(MaterialTheme.colorScheme.background),
            contentAlignment = Alignment.Center
        ) {
            //image

            Column(
                Modifier
                    .fillMaxWidth()
                    .fillMaxHeight(0.4f)
                    .align(Alignment.TopCenter)
            ) {
                Image(
                    painter = painterResource(R.drawable.ph_elder_technology),
                    contentDescription = "Background Image",
                    modifier = Modifier.fillMaxSize(),
                    contentScale = ContentScale.Crop
                )
            }
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 24.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {

                // Logo (replace with your drawable)
                Box(
                    Modifier
                        .padding(bottom = 30.dp)
                ){
                    Column(
                        Modifier
                            .fillMaxWidth(0.38f)
                            .aspectRatio(1f)
                            .clip(CircleShape)
                            .background(MaterialTheme.colorScheme.surface)
                            .align(Alignment.Center)
                    ) { }
                    Image(
                        painter = painterResource(id = R.drawable.ic_logo_bare),
                        contentDescription = "App Logo",
                        modifier = Modifier
                            .fillMaxWidth(0.24f)
                            .align(Alignment.Center)
                    )
                }

                // Headline
                Text(
                    text = stringResource(R.string.login_title),
                    fontSize = 24.sp,
                    fontWeight = FontWeight.Bold,
                    textAlign = TextAlign.Center
                )

                Spacer(modifier = Modifier.height(12.dp))

                // Subtext
                Text(
                    text = stringResource(R.string.login_sub),
                    fontSize = 14.sp,
                    textAlign = TextAlign.Center
                )

                Spacer(modifier = Modifier.height(80.dp))

                // Google Button
                Button(
                    onClick = {
                        if (state.isLoading){

                        }else{
                            launchGoogleSignIn()
                        }
                    },
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(56.dp),
                    shape = RoundedCornerShape(28.dp),
                    colors = ButtonDefaults.buttonColors(
                        containerColor = MaterialTheme.colorScheme.surface
                    ),
                    elevation = ButtonDefaults.buttonElevation(4.dp)
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        if (state.isLoading){
                            CircularProgressIndicator(
                                Modifier.size(20.dp)
                            )
                        }else{
                            Image(
                                painter = painterResource(id = R.drawable.ic_google),
                                contentDescription = "Google",
                                modifier = Modifier.size(20.dp)
                            )
                        }

                        Spacer(modifier = Modifier.width(12.dp))

                        Text(
                            text = stringResource(R.string.login_button),
                            fontWeight = FontWeight.Medium,
                            color = MaterialTheme.colorScheme.onSurface
                        )
                    }
                }
            }
        }
    }
}

@Preview
@Composable
private fun LoginScreenPreview() {
    LoginScreen(state = LoginState(), onAction = {})
}